

services:
  rabbitmq:
    container_name: rabbitmq-test
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-test-network
networks:
  rabbitmq-test-network:
    driver: bridge
    name: rabbitmq-test-network
